### PR TITLE
Discard master and slave language

### PR DESCRIPTION
**Pull request by bopopescu**
For diversity reasons, it would be nice to try to avoid 'master' and 'slave' terminology in this repository which can be associated to slavery. The master-slave terminology could be problematic for people in several countries which has the history of slavery like Romania, USA and many others. Thank you for considering the proposal. Let me know if any changes in the PR are needed, I would be happy to implement them.

### CODE REVIEW

**Comment by jesusvasquez333** [comment]
@bopopescu thank you for the suggestion and for bringing this to our attention. We have discussed this and agree with your proposed change. Unfortunately this code uses an external library which defines this API, so eliminating the terminology isn't as straightforward as a search and replace. However, we have discussed it with the owners of the external library, and they are now thinking about how to eliminate the terms there as well. Once that is done, we would be able to eliminate it here as well.

As this change is not possible at this time, I will close this PR, and fix it once the external library is updated. I moved this request to issue #24 so it can be address in the future.

Thank you,
Jesus

**Comment by till-s** [comment]
I would welcome this change, too. I remember many years ago, when I was 
still a kid
in Switzerland and started to dig through the first (TTL) datasheets in 
English I thought
it was strange to find 'Master-Slave Flipflops' there...

My only 2 cents recommendation would be finding new terms that are 
concise. 'Subordinate' is IMHO
too long, I would then go for just 'Sub' (and maybe 'Com'<mander> for 
the peer).
Also, it would be desirable for both names to have the same length for 
sake of
formatting...

Best
-- Till

**Comment by jesusvasquez333** [comment]
Hi @till-s, thank you for your comments and suggestions. 

A couple of week ago the updated the linux kernel coding style documentation (in [this commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=49decddd39e5f6132ccd7d9fdc3d7c470b0061bb)), and they recommend these alternatives:
```
primary,main / secondary,replica,subordinate
initiator,requester / target,responder
controller,host / device,worker,proxy
leader / follower
director / performer
```

**Comment by ruck314** [comment]
image
It appears that ARM is moving `master/slave` to `Requester/Completer` for the AMBA specs.

**Pull request closed without merging**
